# question 4.a bb6nn.l_k_bbknn(l=3) unit tests run correctly how we get an erro from louvain "InternalError: Error at community.c:2677: weights must be positive, Invalid value"
we are able to plot the data however scanpy.tl.umap() returned a error
" RuntimeWarning: divide by zero encountered in true_divide"

I think bug may be self._adata.uns['neighbors']['params']['n_neighbors'] is set to "k", it should be numBatchs*l

sc.tl.louvain(anndata,
                  flavor='igraph',
                  directed=False,
                  use_weights=True)
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<timed eval> in <module>

~/anaconda3/envs/BME-230B-hw2/lib/python3.7/site-packages/scanpy/tools/_louvain.py in louvain(adata, resolution, random_state, restrict_to, key_added, adjacency, flavor, directed, use_weights, partition_type, partition_kwargs, copy)
    136             # adata.uns['louvain_quality'] = part.quality()
    137         else:
--> 138             part = g.community_multilevel(weights=weights)
    139         groups = np.array(part.membership)
    140     elif flavor == 'taynaud':

~/anaconda3/envs/BME-230B-hw2/lib/python3.7/site-packages/igraph/__init__.py in community_multilevel(self, weights, return_levels)
   1156                     modularity_params=dict(weights=weights)))
   1157         else:
-> 1158             membership = GraphBase.community_multilevel(self, weights, False)
   1159             result = VertexClustering(self, membership,
   1160                     modularity_params=dict(weights=weights))

InternalError: Error at community.c:2677: weights must be positive, Invalid value

sc.tl.umap(anndata)

/Users/andrewdavidson/anaconda3/envs/BME-230B-hw2/lib/python3.7/site-packages/scanpy/neighbors/umap/umap_.py:870: RuntimeWarning: invalid value encountered in sqrt
  D = scipy.sparse.spdiags(1.0 / np.sqrt(diag_data), 0, graph.shape[0],
/Users/andrewdavidson/anaconda3/envs/BME-230B-hw2/lib/python3.7/site-packages/scanpy/neighbors/umap/umap_.py:870: RuntimeWarning: divide by zero encountered in true_divide
  D = scipy.sparse.spdiags(1.0 / np.sqrt(diag_data), 0, graph.shape[0],